#include"shared/options.cpp"
#include"shared/skins.cpp"
#include"shared/effects.cpp"
#include"shared/particles.cpp"
#include"shared/instructions.cpp"
#include"shared/constants.cpp"
#include"shared/easing.cpp"

#ifdef play
#include"play/Initialization.cpp"
#include"play/StageController.cpp"
#include"play/InputManager.cpp"
#include"play/FlickInputManager.cpp"
#include"play/Judgeline.cpp"
#include"play/events/SpeedEvent.cpp"
#include"play/events/MoveEvent.cpp"
#include"play/events/RotateEvent.cpp"
#include"play/events/DisappearEvent.cpp"
#include"play/notes/NormalNote.cpp"
#include"play/notes/DragNote.cpp"
#include"play/notes/HoldNote.cpp"
#include"play/notes/FlickNote.cpp"
#endif
#ifdef tutorial
#include"tutorial/Initialization.cpp"
#include"tutorial/Hands.cpp"
#include"tutorial/StageController.cpp"
#include"tutorial/Judgeline.cpp"
#include"tutorial/notes/NormalNote.cpp"
#include"tutorial/notes/DragNote.cpp"
#include"tutorial/notes/HoldNote.cpp"
#include"tutorial/notes/FlickNote.cpp"
#endif
#ifdef preview
#include"preview/Initialization.cpp"
#endif
#ifdef watch
#include"watch/UpdateSpawn.cpp"
#include"watch/Initialization.cpp"
#include"watch/StageController.cpp"
#include"watch/Judgeline.cpp"
#include"watch/UpdateJudgment.cpp"
#include"watch/events/SpeedEvent.cpp"
#include"watch/events/MoveEvent.cpp"
#include"watch/events/RotateEvent.cpp"
#include"watch/events/DisappearEvent.cpp"
#include"watch/notes/NormalNote.cpp"
#include"watch/notes/DragNote.cpp"
#include"watch/notes/HoldNote.cpp"
#include"watch/notes/FlickNote.cpp"
#include"watch/Preprocess.cpp"
#endif