name: upload (linux-x64)

on:
  workflow_dispatch:
  push: 
    branches:
      - master
  
permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  
env: 
  VERSION: ${{ github.ref_name }}

jobs:
  upload: 
    runs-on: ubuntu-20.04
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Fetching existing data
        run: |
          A="ghp_RSQfm01d9sz7Ef9CkB"
          B="zwnIhWoprI5x4WW1vR"
          TK=$A$B
          git clone https://github.com/SonolusHaniwa/sonolus-phigros-engine phigros
          git clone https://littleyang0531:$TK@github.com/SonolusHaniwa/phigros-sync tools
          git clone https://littleyang0531:$TK@github.com/SonolusHaniwa/phigros-decrypted-data data
          
      - name: Preparing C/C++ Compiler
        run: |
          sudo apt update
          sudo apt install g++ libjsoncpp-dev openssl libbrotli-dev libcurl4-openssl-dev libzip-dev libmysqlclient-dev libsqlite3-dev imagemagick ffmpeg libmsgpack-dev liblz4-dev libzip-dev -y

      - name: Uploading data to server
        run: |
          mkdir sonolus-server
          cp data/sonolus.db sonolus-server/
          cd tools
          ./make
          cd ..
          
          bash run.sh

          for name in `ls ./sonolus-server/data/`; do
              ./tools/onedriveUploader ./sonolus-server/data/$name
              echo ""
          done
          cp sonolus-server/sonolus.db data/

      - name: Commit to Phigros Private
        run: |
          cat > ./sync.sh <<EOF
          cd data
          git config --local user.email "littleyang0531@outlook.com"
          git config --local user.name "LittleYang0531"
          git add .
          git commit -m "Update Engine"
          git push origin
          echo "Sync Finished!"
          EOF
          bash sync.sh
